[project]
name = "sync-trakt"
version = "0.1.0"
requires-python = ">=3.10"
description = "A script to sync a CSV file to Trakt.tv"
authors = [
    {name = "Gemini"},
]
dependencies = [
    "trakt==3.4.0",
    "python-dotenv==1.1.1",
]
